name: macos
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
    build:
        name: build-and-install
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: install-cmake
              run: brew install cmake
              
            - name: install-git
              run: brew install git
              
            - name: install-openmp
              run: brew install libomp
              
            - name: install-catch2
              run: brew install catch2
              
            - name: install-pybind11
              run: brew install pybind11
              
            - name: install-eigen3
              run: brew install eigen
            
            - name: install-autodiff
              run: brew install autodiff
            
            - name: install-liblbfgs
              run: |
                git clone https://github.com/chokkan/liblbfgs.git
                cd autodiff
                mkdir .build && cd .build
                cmake ..
                make
                sudo make install
                cd ../..
                rm -rf liblbfgs
                
            - name: compile-and-install
              run: |
                mkdir build && cd build
                cmake ..
                make
                sudo make install

