name: macos
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
    build:
        name: build-and-install
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: install-cmake
              run: brew install cmake
              
            - name: install-git
              run: brew install git
              
            - name: install-openmp
              run: brew install libomp
              
            - name: install-catch2
              run: brew install catch2
              
            - name: install-pybind11
              run: brew install pybind11
            
            - name: install-python-setuptools
              run: |
                brew install python-setuptools
                pip install setuptools
                conda install setuptools
              
            - name: install-eigen3
              run: |
                wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
                tar -xf eigen-3.4.0.tar.gz
                cd eigen-3.4.0
                mkdir .build && cd .build
                cmake ..
                make
                sudo make install
                cd ../..
                rm eigen-3.4.0.tar.gz
                rm -rf eigen-3.4.0
            
            - name: install-autodiff
              run: |
                wget https://github.com/autodiff/autodiff/archive/refs/tags/v1.1.2.tar.gz
                tar -xf v1.1.2.tar.gz
                cd autodiff-1.1.2
                mkdir .build && cd .build
                /opt/homebrew/bin/cmake ..
                sudo /opt/homebrew/bin/cmake --build . --target install
                cd ../..
                rm v1.1.2.tar.gz
                sudo rm -rf autodiff-1.1.2
            
            - name: install-liblbfgs
              run: |
                git clone https://github.com/chokkan/liblbfgs.git
                cd liblbfgs
                mkdir .build && cd .build
                cmake ..
                make
                sudo make install
                cd ../..
                rm -rf liblbfgs
                
            - name: compile-and-install
              run: |
                mkdir build && cd build
                cmake ..
                make
                sudo make install

